### ISSUE TITLE
Error executing zones or target

### ISSUE THREAD

**Issue by Martinvdm** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#2]
Hi

i can't get the module working. having the following config:
```
      - type: custom:xiaomi-vacuum-map-card
        entity: vacuum.xiaomi_vacuum
        map_image: '/local/img/xiaomi_vacuum_map_card3.png'
        base_position:
          x: 605
          y: 453
        reference_point:
          x: 682
          y: 370
        zones:
          - [[19032,28186,21082,30686,1]]
          - [[22559,28852,26759,30952,1]]
          - [[18328,24990,21678,28140,1],[21682,25004,26682,28854,1]]
```
when executing a zone cleanup the following error occurs:
```
2019-08-12 21:56:50 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.139765962472976] None @ data['zone'][0]
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/components/websocket_api/commands.py", line 121, in handle_call_service
    connection.context(msg))
  File "/usr/src/app/homeassistant/core.py", line 1130, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 267, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 589, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 427, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: None @ data['zone'][0]
```

when using the go to target function, nothing happens, no logging at all.

**Comment by PiotrMachowski** [comment]
The problem is with zoned cleanup is that zones you have defined have 5 parameters instead of 4 (additional `1`).
Could you confirm if it solves your problem?

**Comment by Martinvdm** [comment]
I didn’t notice this, as i copied the zone info from flolevac. After removing the ‘,1’ at the and of the zones I do not get any error any more. Thanks!
