### ISSUE TITLE
Error "cannot convert dictionary update sequence element #0 to a sequence" when setting it up

### ISSUE THREAD

**Issue by bartekd123** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#40]
I am trying to get this working. I have my lovelace config pretty basic. When I try either go to target, or zone cleanup, I get the error in the subject. I tried adding the python script, updating scripts.yaml with the 2 sets of examples, but it doesn't work either. Wondering if I am missing something?

Here is my Yaml, and the full error from HA.

```
      - calibration_points:
          - map:
              x: 360
              'y': 135
            vacuum:
              x: 27757
              'y': 19265
          - map:
              x: 365
              'y': 341
            vacuum:
              x: 27797
              'y': 25653
          - map:
              x: 614
              'y': 346
            vacuum:
              x: 34826
              'y': 25593
        debug: false
        entity: vacuum.rockrobo
        map_image: /local/floorplan/floorplan_house.png
        type: 'custom:xiaomi-vacuum-map-card'
```

```
cannot convert dictionary update sequence element #0 to a sequence
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1226, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1251, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 201, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 335, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 357, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/vacuum/schema_state.py", line 404, in async_send_command
    message.update(params)
TypeError: cannot convert dictionary update sequence element #0 to a sequence
```

**Comment by PiotrMachowski** [comment]
It seems that you are using mqtt vacuum, have you tried using miio version?

**Comment by bartekd123** [comment]
Hi @PiotrMachowski 
No I didn't, and didn't know about it. I just tested it, and that did the trick. Changed my configuration file from platform: mqtt to be xiaomi_miio

thanks for your help!

**Comment by PiotrMachowski** [comment]
Happy to help :)
